### ISSUE TITLE
Does the package work properly when using Windows and Korean MeCab?

### ISSUE THREAD

**Issue by paithiov909** [junhewk/RcppMeCab#10]
You know, only when using windows, the package uses pre-packaged `libmecab.dll` for its compiling.
This approach is now quite fine so that the package works well when using 64bit Windows and MeCab for Japanese.

However, it still has some troubles using Windows and Korean MeCab.

I tried to use `RcppMeCab::pos` with Korean MeCab and mecab-ko-dic under my local machine,
it occured an Exception and returned nothing.

**Comment by junhewk** [comment]
As you know, `RcppMeCab::pos` and other functions depend on installed MeCab binary. When using RcppMeCab to parse Korean, you need to install MeCab and R in Korean Windows. That is the limit of MeCab itself.

Current Github version works well in Windows 64 bit (Korean).

![image](https://user-images.githubusercontent.com/16641432/104868907-fa50fa00-5987-11eb-8ac0-79f29a57f51c.png)

Thank you for your contribution. I really appreciate it.
