### ISSUE TITLE
Why columns in resulting data.frame are all integers?

### ISSUE THREAD

**Issue by koheiw** [junhewk/RcppMeCab#6]
`pos()` retuns a data.frame but its columns are all integers. I think it should have columns in the following format:
```
doc_id: factor
sentence_id: integer
token_id: integer
token: character
subtype: character
analytic: character
```

**Comment by junhewk** [comment]
I was incredibly busy for writing up my dissertation. Now things settled up. I'll work on the things you flagged. I'm so sorry to reply this late.

**Comment by junhewk** [comment]
Finally I change the output of data.frame as you requested. doc_id column contains input text as factor format. My apology for this delay (already 5 years have been passed after you requested)!

**Comment by koheiw** [comment]
Thanks! I think we have feature requests for our packages older than five years 😁
